dico_albums = {
    "12-Bar Original": "Anthology 2",
    "Across the Universe": "Let It Be",
    "Act Naturally": "Help!",
    "Ain't She Sweet": "Anthology 1",
    "All I've Got to Do": "With the Beatles",
    "All My Loving": "With the Beatles",
    "All Things Must Pass": "Anthology 3",
    "All Together Now": "Yellow Submarine",
    "All You Need Is Love": "Magical Mystery Tour",
    "And I Love Her": "A Hard Day's Night",
    "And Your Bird Can Sing": "Revolver",
    "Anna (Go to Him)": "Please Please Me",
    "Another Girl": "Help!",
    "Any Time at All": "A Hard Day's Night",
    "Ask Me Why": "Please Please Me",
    "Baby It's You": "Please Please Me",
    "Baby, You're a Rich Man": "Magical Mystery Tour",
    "Baby's in Black": "Beatles for Sale",
    "Back in the U.S.S.R.": "The Beatles",
    "Bad Boy": "A Collection of Beatles Oldies",
    "Bad to Me": "The Beatles Bootleg Recordings 1963",
    "The Ballad of John and Yoko": "1967-1970",
    "Beautiful Dreamer": "On Air - Live at the BBC Volume 2",
    "Because": "Abbey Road",
    "Because I Know You Love Me So": "Let It Be... Naked - Fly on the Wall bonus disc",
    "Being for the Benefit of Mr. Kite!": "Sgt. Pepper's Lonely Hearts Club Band",
    "Besame Mucho": "Anthology 1",
    "Birthday": "The Beatles",
    "Blackbird": "The Beatles",
    "Blue Jay Way": "Magical Mystery Tour",
    "Boys": "Please Please Me",
    "Can't Buy Me Love": "A Hard Day's Night",
    "Carol": "Live at the BBC",
    "Carry That Weight": "Abbey Road",
    "Catswalk": "Unknown",
    "Cayenne": "Anthology 1",
    "Chains": "Please Please Me",
    "Child of Nature": "Let It Be... Naked - Fly on the Wall bonus disc",
    "Christmas Time (Is Here Again)": "The Beatles' Christmas Album",
    "Circles": "Unknown",
    "Clarabella": "Live at the BBC",
    "Come and Get It": "Anthology 3",
    "Come Together": "Abbey Road",
    "The Continuing Story of Bungalow Bill": "The Beatles",
    "Cry Baby Cry": "The Beatles",
    "Cry for a Shadow": "Anthology 1",
    "Crying, Waiting, Hoping": "Live at the BBC",
    "A Day in the Life": "Sgt. Pepper's Lonely Hearts Club Band",
    "Day Tripper": "A Collection of Beatles Oldies",
    "Dear Prudence": "The Beatles",
    "Devil in Her Heart": "With the Beatles",
    "Dig a Pony": "Let It Be",
    "Dig It": "Let It Be",
    "Dizzy, Miss Lizzy": "Help!",
    "Do You Want to Know a Secret?": "Please Please Me",
    "Doctor Robert": "Revolver",
    "Don't Bother Me": "With the Beatles",
    "Don't Ever Change": "Live at the BBC",
    "Don't Let Me Down": "1967-1970",
    "Don't Pass Me By": "The Beatles",
    "Drive My Car": "Rubber Soul",
    "Eight Days a Week": "Beatles for Sale",
    "Eleanor Rigby": "Revolver",
    "The End": "Abbey Road",
    "Etcetera": "Unreleased",
    "Every Little Thing": "Beatles for Sale",
    "Everybody's Got Something to Hide Except Me and My Monkey": "The Beatles",
    "Everybody's Trying to Be My Baby": "Beatles for Sale",
    "Fixing a Hole": "Sgt. Pepper's Lonely Hearts Club Band",
    "Flying": "Magical Mystery Tour",
    "The Fool on the Hill": "Magical Mystery Tour",
    "For No One": "Revolver",
    "For You Blue": "Let It Be",
    "Free as a Bird": "Anthology 1",
    "From Me to You": "A Collection of Beatles Oldies",
    "From Us to You": "Live at the BBC",
    "Get Back": "Let It Be",
    "Getting Better": "Sgt. Pepper's Lonely Hearts Club Band",
    "Girl": "Rubber Soul",
    "Glad All Over": "Live at the BBC",
    "Glass Onion": "The Beatles",
    "Golden Slumbers": "Abbey Road",
    "Good Day Sunshine": "Revolver",
    "Good Morning Good Morning": "Sgt. Pepper's Lonely Hearts Club Band",
    "Good Night": "The Beatles",
    "Goodbye": "Unknown",
    "Got to Get You into My Life": "Revolver",
    "Hallelujah, I Love Her So": "Anthology 1",
    "Happiness Is a Warm Gun": "The Beatles",
    "A Hard Day's Night": "A Hard Day's Night",
    "Heather": "Unknown",
    "Hello, Goodbye": "Magical Mystery Tour",
    "Hello Little Girl": "Anthology 1",
    "Help!": "Help!",
    "Helter Skelter": "The Beatles",
    "Her Majesty": "Abbey Road",
    "Here Comes the Sun": "Abbey Road",
    "Here, There and Everywhere": "Revolver",
    "Hey Bulldog": "Yellow Submarine",
    "Hey Jude": "1967-1970",
    "Hippy Hippy Shake": "Live at the BBC",
    "Hold Me Tight": "With the Beatles",
    "Honey Don't": "Beatles for Sale",
    "Honey Pie": "The Beatles",
    "The Honeymoon Song": "Live at the BBC",
    "How Do You Do It?": "Anthology 1",
    "I Am the Walrus": "Magical Mystery Tour",
    "I Call Your Name": "Long Tall Sally EP",
    "I Don't Want to Spoil the Party": "Beatles for Sale",
    "I Feel Fine": "A Collection of Beatles Oldies",
    "I Forgot to Remember to Forget": "Live at the BBC",
    "I Got a Woman": "Live at the BBC",
    "I Got to Find My Baby": "Live at the BBC",
    "I Just Don't Understand": "Live at the BBC",
    "I Lost My Little Girl": "Unknown",
    "I Me Mine": "Let It Be",
    "I Need You": "Help!",
    "I Saw Her Standing There": "Please Please Me",
    "I Should Have Known Better": "A Hard Day's Night",
    "I Wanna Be Your Man": "With the Beatles",
    "I Want to Hold Your Hand": "A Collection of Beatles Oldies",
    "I Want to Tell You": "Revolver",
    "I Want You (She's So Heavy)": "Abbey Road",
    "I Will": "The Beatles",
    "If I Fell": "A Hard Day's Night",
    "If I Needed Someone": "Rubber Soul",
    "If You've Got Trouble": "Anthology 2",
    "I'll Be Back": "A Hard Day's Night",
    "I'll Be on My Way": "Live at the BBC",
    "I'll Cry Instead": "A Hard Day's Night",
    "I'll Follow the Sun": "Beatles for Sale",
    "I'll Get You": "Past Masters Volume 1",
    "I'll Keep You Satisfied": "Unknown",
    "I'm a Loser": "Beatles for Sale",
    "I'm Down": "Rock 'n' Roll Music",
    "I'm Gonna Sit Right Down and Cry (Over You)": "Live at the BBC",
    "I'm Happy Just to Dance with You": "A Hard Day's Night",
    "I'm In Love": "The Beatles Bootleg Recordings 1963",
    "I'm Looking Through You": "Rubber Soul",
    "I'm Only Sleeping": "Revolver",
    "I'm So Tired": "The Beatles",
    "I'm Talking About You": "Live! at the Star-Club in Hamburg, Germany; 1962",
    "In My Life": "Rubber Soul",
    "In Spite of All the Danger": "Anthology 1",
    "The Inner Light": "Rarities",
    "It Won't Be Long": "With the Beatles",
    "It's All Too Much": "Yellow Submarine",
    "It's Only Love": "Help!",
    "I've Got a Feeling": "Let It Be",
    "I've Just Seen a Face": "Help!",
    "Jazz Piano Song": "Let it Be film",
    "Jessie's Dream": "Magical Mystery Tour",
    "Johnny B. Goode": "Live at the BBC",
    "Julia": "The Beatles",
    "Junk": "Anthology 3",
    "Kansas City/Hey-Hey-Hey-Hey!": "Beatles for Sale",
    "Keep Your Hands Off My Baby": "Live at the BBC",
    "Komm, gib mir deine Hand": "Rarities",
    "Lady Madonna": "1967-1970",
    "Leave My Kitten Alone": "Anthology 1",
    "Lend Me Your Comb": "Anthology 1",
    "Let It Be": "Let It Be",
    "Like Dreamers Do": "Anthology 1",
    "Little Child": "With the Beatles",
    "Lonesome Tears in My Eyes": "Live at the BBC",
    "The Long and Winding Road": "Let It Be",
    "Long, Long, Long": "The Beatles",
    "Long Tall Sally": "Long Tall Sally EP",
    "Looking Glass": "Unknown",
    "Love Me Do": "Please Please Me",
    "Love of the Loved": "Unknown",
    "Love You To": "Revolver",
    "Lovely Rita": "Sgt. Pepper's Lonely Hearts Club Band",
    "Lucille": "Live at the BBC",
    "Lucy in the Sky with Diamonds": "Sgt. Pepper's Lonely Hearts Club Band",
    "Madman": "Unknown",
    "Maggie Mae": "Let It Be",
    "Magical Mystery Tour": "Magical Mystery Tour",
    "Mailman, Bring Me No More Blues": "Anthology 3",
    "Martha My Dear": "The Beatles",
    "Matchbox": "Long Tall Sally EP",
    "Maxwell's Silver Hammer": "Abbey Road",
    "Mean Mr. Mustard": "Abbey Road",
    "Memphis, Tennessee": "Live at the BBC",
    "Michelle": "Rubber Soul",
    "Misery": "Please Please Me",
    "Money (That's What I Want)": "With the Beatles",
    "Moonlight Bay": "Anthology 1",
    "Mother Nature's Son": "The Beatles",
    "Mr. Moonlight": "Beatles for Sale",
    "My Bonnie": "Anthology 1",
    "The Night Before": "Help!",
    "No Reply": "Beatles for Sale",
    "Norwegian Wood (This Bird Has Flown)": "Rubber Soul",
    "Not a Second Time": "With the Beatles",
    "Not Guilty": "Anthology 3",
    "Nothin' Shakin' (But the Leaves on the Trees)": "Live at the BBC",
    "Nowhere Man": "Rubber Soul",
    "Ob-La-Di, Ob-La-Da": "The Beatles",
    "Octopus's Garden": "Abbey Road",
    "Oh! Darling": "Abbey Road",
    "Old Brown Shoe": "1967-1970",
    "One After 909": "Let It Be",
    "One and One Is Two": "Unknown",
    "Only a Northern Song": "Yellow Submarine",
    "Ooh! My Soul": "Live at the BBC",
    "Paperback Writer": "A Collection of Beatles Oldies",
    "Penny Lane": "Magical Mystery Tour",
    "Piggies": "The Beatles",
    "Please Mr. Postman": "With the Beatles",
    "Please Please Me": "Please Please Me",
    "Polythene Pam": "Abbey Road",
    "P.S. I Love You": "Please Please Me",
    "Rain": "Rarities",
    "Real Love": "Anthology 2",
    "Revolution": "1967-1970",
    "Revolution 1": "The Beatles",
    "Revolution 9": "The Beatles",
    "Rip It Up/Shake, Rattle, and Roll/Blue Suede Shoes": "Anthology 3",
    "Rock and Roll Music": "Beatles for Sale",
    "Rocky Raccoon": "The Beatles",
    "Roll Over Beethoven": "With the Beatles",
    "Run for Your Life": "Rubber Soul",
    "Savoy Truffle": "The Beatles",
    "Searchin'": "Anthology 1",
    "September in the Rain": "Unknown",
    "Sexy Sadie": "The Beatles",
    "Sgt. Pepper's Lonely Hearts Club Band": "Sgt. Pepper's Lonely Hearts Club Band",
    "Sgt. Pepper's Lonely Hearts Club Band (Reprise)": "Sgt. Pepper's Lonely Hearts Club Band",
    "Shakin' in the Sixties": "Unreleased",
    "She Came in Through the Bathroom Window": "Abbey Road",
    "She Loves You": "A Collection of Beatles Oldies",
    "She Said She Said": "Revolver",
    "She's a Woman": "Rarities",
    "She's Leaving Home": "Sgt. Pepper's Lonely Hearts Club Band",
    "The Sheik of Araby": "Anthology 1",
    "A Shot of Rhythm and Blues": "Live at the BBC",
    "Shout": "Anthology 1",
    "Sie liebt dich": "Rarities",
    "Slow Down": "Long Tall Sally EP",
    "So How Come (No One Loves Me)": "Live at the BBC",
    "Soldier of Love (Lay Down Your Arms)": "Live at the BBC",
    "Some Other Guy": "Live at the BBC",
    "Something": "Abbey Road",
    "Sour Milk Sea": "Unreleased",
    "Step Inside Love/Los Paranoias": "Anthology 3",
    "Strawberry Fields Forever": "Magical Mystery Tour",
    "Sun King": "Abbey Road",
    "Sure to Fall (in Love with You)": "Live at the BBC",
    "Sweet Little Sixteen": "Live at the BBC",
    "Take Good Care of My Baby": "Unknown",
    "Taking a Trip to Carolina": "Let It Be... Naked - Fly on the Wall bonus disc",
    "A Taste of Honey": "Please Please Me",
    "Taxman": "Revolver",
    "Teddy Boy": "Anthology 3",
    "Tell Me What You See": "Help!",
    "Tell Me Why": "A Hard Day's Night",
    "Thank You Girl": "Rarities",
    "That Means a Lot": "Anthology 2",
    "That'll Be the Day": "Anthology 1",
    "That's All Right (Mama)": "Live at the BBC",
    "There's a Place": "Please Please Me",
    "Things We Said Today": "A Hard Day's Night",
    "Think for Yourself": "Rubber Soul",
    "This Boy": "Rarities",
    "Three Cool Cats": "Anthology 1",
    "Ticket to Ride": "Help!",
    "Till There Was You": "With the Beatles",
    "To Know Her is to Love Her": "Live at the BBC",
    "Tomorrow Never Knows": "Revolver",
    "Too Much Monkey Business": "Live at the BBC",
    "Twist and Shout": "Please Please Me",
    "Two of Us": "Let It Be",
    "Wait": "Rubber Soul",
    "Watching Rainbows": "Unknown",
    "We Can Work It Out": "A Collection of Beatles Oldies",
    "What Goes On": "Rubber Soul",
    "What You're Doing": "Beatles for Sale",
    "What's The New Mary Jane": "Anthology 3",
    "When I Get Home": "A Hard Day's Night",
    "When I'm Sixty-Four": "Sgt. Pepper's Lonely Hearts Club Band",
    "While My Guitar Gently Weeps": "The Beatles",
    "Why Don't We Do It in the Road?": "The Beatles",
    "Wild Honey Pie": "The Beatles",
    "With a Little Help from My Friends": "Sgt. Pepper's Lonely Hearts Club Band",
    "Within You Without You": "Sgt. Pepper's Lonely Hearts Club Band",
    "Woman": "Let It Be film",
    "The Word": "Rubber Soul",
    "Words of Love": "Beatles for Sale",
    "Yellow Submarine": "Revolver",
    "Yer Blues": "The Beatles",
    "Yes It Is": "Rarities",
    "Yesterday": "Help!",
    "You Can't Do That": "A Hard Day's Night",
    "You Know My Name (Look Up the Number)": "Rarities",
    "You Know What to Do": "Anthology 1",
    "You Like Me Too Much": "Help!",
    "You Never Give Me Your Money": "Abbey Road",
    "You Won't See Me": "Rubber Soul",
    "You'll Be Mine": "Anthology 1",
    "Young Blood": "Live at the BBC",
    "Your Mother Should Know": "Magical Mystery Tour",
    "You're Going to Lose That Girl": "Help!",
    "You've Got to Hide Your Love Away": "Help!",
    "You've Really Got a Hold on Me": "With the Beatles"
}
